export default [
  'Aleaume',
  'Allain',
  'Ballesdens',
  'Barat',
  'Basot',
  'Benedicti',
  'Bennart',
  'Berruyer',
  'Bouchelu',
  'Boucher',
  'Bouraine',
  'Bourdin',
  'Broichet',
  'Camus',
  'Carreau',
  'Cayn',
  'Chausse',
  'Chrestien',
  'Corneul',
  'Cosson',
  'Cousin',
  'Dampmartin',
  'Daumont',
  'Daval',
  'deBailly',
  'deBirague',
  'deBourbon',
  'deChiverny',
  'deDormans',
  'deGuise',
  'de la Chapelle aux Ursins',
  'de la Guesle',
  'de Lansac',
  'de Lassus',
  'de Lenoncourt',
  'de Lorraine',
  'de Lyon',
  'de Malicorne',
  'de Mayenne',
  'de Pectu',
  'de Poretus',
  'de Quitte',
  'de Rambouillet',
  'de Rosiere',
  'de Ruffec',
  'de Schomberg',
  'de Thou',
  'de Varade',
  'de Vaudemont',
  'de Villequier',
  'des Chasteliers',
  'Desiré',
  'd\'Espesse',
  'Des-prez',
  'du Guet',
  'du Mesnil',
  'Everard',
  'Falaize',
  'Faulcon',
  'Faye',
  'Fournier',
  'Gaillard',
  'Gauthier',
  'Gemelli',
  'Godier',
  'Goux',
  'Groult',
  'Guilland',
  'Guychenot',
  'Idoine',
  'la Guesle',
  'le Febure',
  'le Hongre',
  'le Maistre',
  'Maceré',
  'Maheur',
  'Maillard',
  'Moreau',
  'Muldrac',
  'Nicolas',
  'Paillet',
  'Paris',
  'Pelletier',
  'Peron',
  'Pugnance',
  'Rouzee',
  'Tanquerel',
  'Thierry',
  'Viel',
  'Vigneron',
  'Violet'
]